CREATE TABLE binance_ticker (
  id SERIAL PRIMARY KEY,
  exchange VARCHAR(120) NOT NULL,
  pair VARCHAR(10) NOT NULL,
  base VARCHAR(10) NOT NULL,
  quote VARCHAR(10) NOT NULL,
  timestamp BIGINT NOT NULL,
  last NUMERIC(10, 4),
  open_price NUMERIC(10, 4),
  close_price NUMERIC(10,4),
  high_price NUMERIC(10,4),
  low_price NUMERIC(10,4),
  volume NUMERIC(10,4),
  quote_volume NUMERIC(10,4),
  change NUMERIC(10,4),
  change_percent NUMERIC(10,4),
  bid_price NUMERIC(10,4),
  ask_price NUMERIC(10,4),
  ask_volume NUMERIC(10,4)
);