service: crypto-arb-api

provider:
  name: aws
  runtime: nodejs12.x
  region: 'eu-west-2'
  frameworkVersion: ">=1.43.0"
  environment:
    DB_HOST: ${file(./secrets.json):DB_HOST}
    DB_PASS: ${file(./secrets.json):DB_PASS}
    DB_USER: ${file(./secrets.json):DB_USER}
    DB_NAME: ${file(./secrets.json):DB_NAME}
    NODE_ENV: production
functions:
  cryptoArbApi:
    handler: server.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'